### PR TITLE
ec+3,Deprecated - do not use (Was Enhanced AC-3 audio with JOC), ,

### PR DESCRIPTION
**Pull request by jasonkopp**
ec+3 has been deprecated. Modified the sample-entries.csv file accordingly.

### CODE REVIEW

**Comment by mikedo** [comment]
There is no ETSI spec that ever documented ‘ec+3’.  I appreciate retaining documentation of past registrations, but "deprecated" implies that it was in use and should no longer be used. This is a case where it is unlikely/improbable that it was actually deployed. So, maybe "withdrawn, unused, do not use" with no spec reference (since there isn't one).

**Comment by dwsinger** [comment]
I'm fine with "withdrawn, unused, do not use (Was Enhanced AC-3 audio with JOC)".  I don't see any point in linking to a spec. that doesn't mention the code-point.

**Comment by mikedo** [comment]
The original PR was approved, which is not consistent with this comment thread. Who is responsible for revising the PR?

**Comment by cconcolato** [comment]
Can you propose an update?

**Comment by dwsinger** [comment]
> Can you propose an update?

see above https://github.com/mp4ra/mp4ra.github.io/pull/37#issuecomment-494455472

is that acceptable?

**Comment by cconcolato** [comment]
@jasonkopp can you update the pull request to replace "Deprecated - do not use (Was Enhanced AC-3 audio with JOC)" with "withdrawn, unused, do not use"

**Comment by dwsinger** [comment]
I think I need to be pretty firm on keeping the "was" clause. I don't want to set a bad precedent of untraceability here

**Comment by jasonkopp** [comment]
@cconcolato and @dwsinger, I updated the CSV row with your suggestions.

**Comment by mikedo** [comment]
Hmm.  "was" what? Was anticipated by several companies, but "was" never documented in the citation?  And where would one get "Enhanced AC-3 audio with JOC", and what version has it (none)?  Let's not get carried away with the history which was sketchy. Historical researchers would not in fact be able to trace this as proposed.

**Comment by dwsinger** [comment]
I realize that in this case there is a vanishingly small chance of tracing; however, I think we need to set a precedent, that all withdrawals and so on maintain some trace of documentation of what the code was registered for. It won't happen here, but if someone comes across a withdrawn code in the wild, in a file, they should be able to find out "that used to be registered as a MumbleLoudly audio stream". I'm not trying to deal with a problem with _this_ withdrawal of registration; I am trying to set a precedent for withdrawals in general.

**Comment by mikedo** [comment]
I appreciate the principle, but in this case you are inferring trace that does not actually exist. There should not be future phone calls to Dolby inquiring about this code point.  I think the level of traceability should be addressed sensibly case by case if/when there is ever a second one (that a registrant confesses to).

**Comment by dwsinger** [comment]
I think the only chance that Dolby will get contacted (how?) over this code is if you are wrong, and there are instances of use, whereupon contact is justified and maybe needed. In a sense, you are making my point.

**Comment by mikedo** [comment]
So there will not be a reference associated (i.e. not a pointer to the Dolby internal licensing URL)?  OK. Then, merging the comments, the current proposal is: "withdrawn, unused, do not use (was Enhanced AC-3 audio with JOC)", right?  I minor comment - It never "was" this, but it was proposed to be, so how about: "withdrawn, unused, do not use (was proposed for Enhanced AC-3 audio with JOC)". Does that work?

**Comment by dwsinger** [comment]
yes, I think dropping a reference for withdrawn code-points makes sense. so no Dolby pointer. I don't think we need to get into the weeds of "was" -- it was (for better or worse) registered...the fact it wasn't documented or used is off my scope as the RA!

**Comment by mikedo** [comment]
OK, then agreed: "withdrawn, unused, do not use (was Enhanced AC-3 audio with JOC)"

**Pull request merged**
