### PR TITLE
Adds slh1 and slh2 to brands. Adds SL-HDR1 and SL-HDR2 to specifications

### PR DESCRIPTION
**Pull request by jasonkopp**
Do not complete pull request until the update to ETSI spec that they link to is available.

### CODE REVIEW

**Comment by jasonkopp** [comment]
I believe we were waiting for that source to be updated to include slh1... Seems we are still waiting. Not sure the best course of action for this PR.

**Comment by dehaanw** [comment]
Here's the link to the updated version of the ETSI document, now including slh1 and slh2:
https://docbox.etsi.org/Broadcast/Open/ts_10343301v010203_StableDraft.pdf

**Comment by dwsinger** [comment]
docbox does not appear to be a permanent link. we are waiting to be able to link to the specification that contains the definition…

**Comment by dehaanw** [comment]
The stable draft, for which I provided the link, contains the definition. I'll provide the link to the final published document when it becomes available.

**Comment by dwsinger** [comment]
@dehaanw ping for the stable link?

**Comment by dehaanw** [comment]
The stable link is due within a few weeks from now.

**Comment by dehaanw** [comment]
The stable link is now available:
https://www.etsi.org/deliver/etsi_ts/103400_103499/10343301/01.03.01_60/ts_10343301v010301p.pdf
The relevant information is in Annex H.

**Comment by dehaanw** [comment]
OK, can do that. Note that slh1/2/3 are all defined in the same document (part 1). For slh2 and slh3 there are references to part 2 and 3, but those referred docs do not mention the 4CC. So correct way is to just use part 1 as reference for mp4ra. Agree?

**Comment by dehaanw** [comment]
Three new pull requests have been created. The one for slh1 includes the addition of the specification. The changes for slh2 and slh3 include the changes for slh1. Hope this works.
#38 can be dropped.

**Comment by dwsinger** [comment]
closing with no action, superseded by more recent pull requests

**Pull request closed without merging**
