### PR TITLE
Adding the Partial File Format to specifications.csv

### PR DESCRIPTION
**Pull request by jasonkopp**
Adding the Partial File Format to specifications.csv and fixes order of other specs.

### CODE REVIEW

**Comment by cconcolato** [comment]
ping @jeanlf

**Comment by dwsinger** [comment]
Note that the actual commits for the codes defined will come later...

**Comment by jeanlf** [comment]
sorry I missed this one, I added PFF in the specifications.csv in the PR #66 - we should close this one once #66 is merged

**Comment by dwsinger** [comment]
Done in the Pull Request that submitted the Part FF codes

**Pull request closed without merging**
