### PR TITLE
Adding CMAF brands

### LINKED ISSUE #19: 23000-19 CMAF needs to be scanned
and have its code-points added (notably brands)

### PR DESCRIPTION
**Pull request by cconcolato**
Closes #19

### CODE REVIEW

**Comment by mikedo** [comment]
Since there will likely be more than a few of these, maybe a more structured description would be helpful. Maybe something of the form: "CMAF" <kind> <detail>. So instead of "AVC HD CMAF Media Profile", it would be: "CMAF Media Profile - AVC HD".

For ccea, I recommend "CMAF Supplemental Data - 608/708".  Everything is "in track".

CAEP and CDes are lexically out of order. They would precede any ones beginning with lower case  'c'.

**Comment by mikedo** [comment]
cmfc is repeated 3x - 2 of them should be cmfs and cmfl.

im1i is repeated - one of them should be im1t.

Should we do DAM1 now? csh1, camc, cama, cmhs, cmhm

Want help?

**Comment by cconcolato** [comment]
@mikedo Better?

**Comment by mikedo** [comment]
Yep.  Will the AMD1 brands be in a separate pull?

**Comment by dwsinger** [comment]
I think we should do AMD1 when it's FDAM or later

**Pull request merged**
