### PR TITLE
add item_type entries from ISO/IEC 23008-12:2022

### PR DESCRIPTION
**Pull request by bradh**

### CODE REVIEW

**Comment by podborski** [comment]
Thanks. I think there are more missing 4CCs. For example:

- 'mskC'
- 'vvcC'
- 'evcC'

**Comment by bradh** [comment]
> Thanks. I think there are more missing 4CCs. For example:
> 
>     * 'mskC'
> 
>     * 'vvcC'
> 
>     * 'evcC'

That is valid. I was very focused on the `rgan` item type, and just threw in the others because they were there (and removed `'uri '` because it flunked the CI check.

Do you know of a summary document for HEIF ed 1 to ed 2?

**Comment by bradh** [comment]
@podborski Did you have additional review comments on this?

**Comment by bradh** [comment]
I don't think I pulled in anything from CMAF - I don't think I actually have a copy of that.

**Comment by bradh** [comment]
Oh, I see why it looks like it has CMAF updates. I've put a few entries that were at the end of the brands file that were out of alphabetical order into order, and those were CMAF related.

**Pull request merged**
