### PR TITLE
adding 4CCs for HEIF 2nd Edition

### PR DESCRIPTION
**Pull request by cconcolato**

### CODE REVIEW

**Comment by cconcolato** [comment]
ping @jeanlf

**Comment by dwsinger** [comment]
Um, the JPEG sequence brand is jpgs in my copy, not jpes.

"The brand 'jpgs' is specified in the following subclauses."

**Comment by cconcolato** [comment]
@dwsinger right, fixed.

**Comment by cconcolato** [comment]
ping @dwsinger @edrthomas @jeanlf

**Pull request merged**
