### PR TITLE
Missing empty field in sample-entries.csv

### PR DESCRIPTION
**Pull request by edrthomas**

### CODE REVIEW

**Comment by dwsinger** [comment]
odd. most other lines don't have this empty field, and the line it's replacing doesn't either...

**Comment by edrthomas** [comment]
Yes odd indeed ...

I noticed all the builds were failing like this:

image

And this since the commit 8bfa9d4c31041d1ba56e34d7eea73acdff7a8cdd. 

So when looking at, I see that the new line has one field too few:
image

Which would be consistent with the error of the script, trying to access the last field (ObjectType) which in this case does not exist.

Adding an empty field does fix the script crash but now the issue is that the 'empty' spec is not valid according to the validation script which is correct ... 

image


Maybe @jasonkopp , can you look at how to best handle this case in your script ? I.e. how to handle a deprecated line which may not have a valid spec name.

**Comment by dwsinger** [comment]
Ah, maybe for now we need a fake "deprecated" spec entry that deprecated entries can link to?

**Comment by dwsinger** [comment]
edited in place. failing Travis checks may need re-submission.

**Comment by edrthomas** [comment]
Thanks Dave. Your fix does the trick ! I also restarted the builds for open PRs. They are now successful.

**Comment by jasonkopp** [comment]
Hello! You guys were all very active early this morning! Thanks for finding the issue. I assume this is all now resolved.

**Pull request closed without merging**
